const userRouter = require("./user");
const categoriesRouter = require("./categories");
const productRouter = require("./product");
const orderRouter = require("./order");
const eventRouter = require("./event");
const questionRouter = require("./question");
const sliderRouter = require("./slider");
const transportFeeRouter = require("./transportfee");
const paymentRouter = require("./vnpay");
const conversationRouter = require("./convertion");
const messageRouter = require("./message");
const blogRouter = require("./blog");
const couponsRouter = require("./coupon");
const receiptsRouter = require("./receipt");
const inittalRouter = (app) => {
  app.use("/api/v2/user", userRouter);
  app.use("/api/v2/category", categoriesRouter);
  app.use("/api/v2/product", productRouter);
  app.use("/api/v2/order", orderRouter);
  app.use("/api/v2/event", eventRouter);
  app.use("/api/v2/question", questionRouter);
  app.use("/api/v2/slider", sliderRouter);
  app.use("/api/v2/transportfee", transportFeeRouter);
  app.use("/api/v2/payment", paymentRouter);
  app.use("/api/v2/convertion", conversationRouter);
  app.use("/api/v2/message", messageRouter);
  app.use("/api/v2/blog", blogRouter);
  app.use("/api/v2/coupon", couponsRouter);
  app.use("/api/v2/receipt", receiptsRouter);
};
module.exports = inittalRouter;
