export const INCREASE_QUALTTY_CART = "INCREASE_QUALTTY_CART";
export const DECREASE_QUALTTY_CART = "DECREASE_QUALTTY_CART";
export const UPDATE_QUALTTY_CART = "UPDATE_QUALTTY_CART";
export const DELETE_PRODUCT_CART = " DELETE_PRODUCT_CART";

export const GET_DATA_CART = "GET_DATA_CART";
export const CLEAR_QUALTTY_CART = "CLEAR_QUALTTY_CART";
