export const GET_ALL_ORDER_USER = "GET_ALL_ORDER_USER";
export const GET_ALL_ORDER_USER_SUCCESS = "GET_ALL_ORDER_USER_SUCESS";
export const GET_ALL_ORDER_USER_ERROR = "GET_ALL_ORDER_USER_ERROR";

export const GET_ALL_ORDER = "GET_ALL_ORDER";
export const GET_ALL_ORDER_SUCCESS = "GET_ALL_ORDER_SUCESS";
export const GET_ALL_ORDER_ERROR = "GET_ALL_ORDER_USER_ERROR";
