export const LOG_USER = "LOG_USER";
export const LOG_USER_SUCCESS = "LOG_USER_SUCCESS";
export const LOG_USER_ERROR = "LOG_USER_ERROR";
export const LOGOUT_USER = "LOGOUT_USER";
export const LOG_OUT_USER_SUCCESS = "LOG_OUT_USER_SUCCESS";
export const LOG_OUT_USER_ERROR = "LOG_OUT_USER_ERROR";

export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";
